In [11]:
import numpy as np
from sklearn.metrics import confusion_matrix, classification_report, roc_auc_score


In [12]:
np.random.seed(92)
X = np.random.rand(1000, 5)
y = np.random.randint(0, 4, (1000,))


In [13]:
X


array([[8.85880499e-01, 7.88581567e-01, 4.24728131e-01, 4.78869647e-01,
        3.54059732e-04],
       [8.56367046e-01, 3.53321693e-01, 4.86749046e-01, 4.41273106e-01,
        9.38580545e-01],
       [7.17678886e-01, 8.40349164e-01, 2.91518388e-01, 8.35235422e-01,
        4.47437072e-01],
       ...,
       [4.18250104e-01, 7.83031393e-01, 8.64554951e-01, 7.33251456e-01,
        5.15615784e-01],
       [3.26716309e-01, 3.10483811e-01, 4.78642742e-01, 1.07416484e-01,
        2.09666499e-01],
       [2.73479211e-01, 8.52125502e-03, 5.16691941e-01, 2.05249910e-02,
        1.66055148e-01]])

In [14]:
y


array([2, 3, 0, 1, 1, 0, 1, 3, 3, 0, 2, 1, 2, 1, 2, 3, 0, 1, 2, 3, 1, 0,
       0, 2, 1, 1, 1, 3, 0, 0, 3, 0, 0, 0, 0, 1, 0, 2, 3, 3, 1, 0, 2, 2,
       3, 0, 2, 0, 2, 2, 1, 3, 0, 0, 1, 2, 1, 0, 3, 1, 0, 3, 0, 1, 3, 0,
       2, 3, 2, 2, 3, 0, 3, 3, 3, 0, 2, 1, 2, 1, 1, 0, 1, 1, 3, 1, 3, 2,
       2, 3, 0, 0, 2, 1, 3, 3, 3, 0, 0, 2, 0, 1, 3, 0, 1, 2, 0, 2, 0, 0,
       0, 2, 1, 2, 2, 1, 3, 2, 3, 0, 3, 1, 2, 2, 3, 2, 2, 3, 2, 2, 0, 0,
       3, 0, 0, 0, 0, 3, 1, 2, 0, 1, 3, 2, 0, 1, 3, 1, 1, 3, 2, 2, 1, 2,
       2, 1, 1, 2, 3, 0, 0, 1, 1, 2, 0, 1, 3, 3, 2, 1, 2, 0, 0, 1, 0, 1,
       0, 2, 0, 0, 2, 1, 3, 2, 1, 3, 3, 2, 3, 1, 0, 2, 2, 0, 2, 3, 3, 0,
       3, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 1, 1, 3, 1, 0, 0, 3, 0, 3, 2, 3,
       0, 0, 0, 1, 2, 0, 0, 0, 0, 3, 3, 2, 3, 3, 2, 0, 1, 0, 2, 2, 0, 3,
       2, 3, 0, 3, 1, 1, 0, 2, 3, 2, 2, 2, 2, 1, 0, 0, 2, 2, 3, 1, 2, 3,
       2, 2, 2, 1, 1, 3, 0, 2, 3, 2, 0, 3, 0, 1, 0, 2, 2, 0, 1, 0, 0, 1,
       0, 3, 2, 0, 1, 2, 0, 2, 1, 0, 3, 3, 2, 1, 1,

In [15]:
class LogisticRegression:
    def __init__(self, max_iter=200, lr=0.0001):
        self.max_iter = max_iter
        self.lr = lr

    def softmask(self, Z):
        return np.array([np.exp(z) / np.sum(np.exp(z)) for z in Z])

    def loss_function(self, y_true, y_pred):
        return np.sum(np.square(y_true - y_pred)) / (2 * y_true.size)

    def add_intercept(self, X):
        intercept = np.ones(shape=(X.shape[0], 1))
        return np.concatenate((intercept, X), axis=1)

    def fit(self, X, y):
        y_encoded = np.zeros((y.size, y.max() + 1), dtype=int)
        y_encoded[np.arange(y.size), y] = 1
        y = y_encoded
        X = self.add_intercept(X)
        self.theta = np.random.rand(X.shape[1], y.shape[1])

        for iter in range(self.max_iter):
            z = np.dot(X, self.theta)
            h = self.softmask(z)
            self.theta -= self.lr * np.dot(X.T, (h - y)) / y.size
            self.loss = self.loss_function(y, h)

    def predict_prob(self, X):
        X = self.add_intercept(X)
        return self.softmask(np.dot(X, self.theta))

    def predict(self, X):
        pred_prob = self.predict_prob(X)
        pred_argmax = np.argmax(pred_prob, axis=1)
        return pred_argmax

    def confusion_matrix_score(self, y_true, y_pred):
        return confusion_matrix(y_true=y_true, y_pred=y_pred)

    def classification_reports(self, y_true, y_pred):
        return classification_report(y_true=y_true, y_pred=y_pred)


In [16]:
model = LogisticRegression(max_iter=1000, lr=0.000001)
model.fit(X, y)


In [17]:
y_pred = model.predict(X)
confusion = model.confusion_matrix_score(y, y_pred)
confusion


array([[172,  69,  15,   0],
       [162,  66,  14,   0],
       [182,  67,   8,   0],
       [167,  66,  12,   0]], dtype=int64)

In [18]:
y_pred


array([0, 1, 0, 0, 2, 1, 0, 0, 0, 0, 0, 2, 1, 1, 0, 1, 0, 0, 0, 1, 1, 2,
       0, 2, 2, 1, 1, 0, 1, 0, 2, 1, 0, 0, 0, 1, 1, 0, 2, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 2, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 2, 0, 1, 0, 0, 0, 0, 0, 2, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 2, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 2, 0, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 2, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 2, 0, 1, 0,

In [19]:
model.loss_function(y, y_pred)


1.4395

In [20]:
report = model.classification_reports(y, y_pred)
print(report)


              precision    recall  f1-score   support

           0       0.25      0.67      0.37       256
           1       0.25      0.27      0.26       242
           2       0.16      0.03      0.05       257
           3       0.00      0.00      0.00       245

    accuracy                           0.25      1000
   macro avg       0.17      0.24      0.17      1000
weighted avg       0.17      0.25      0.17      1000



e:\TAI\intern lab\week 2\week3_DL\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
e:\TAI\intern lab\week 2\week3_DL\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
e:\TAI\intern lab\week 2\week3_DL\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
